### ISSUE TITLE
Instruments: resource class SOCKET

### ISSUE THREAD

**Issue by leghtas** [Ecpy/ecpy_hqc_legacy#24]
I have an instrument (that for an unknown doesn't communicate properly using LAN VXI), so I set it in SOCKET mode in the Instruments browser (instead of INSTR). I enter the port number, validate, all works fine. When I click ok, the port number is set to 0 (although I entered 5025). And in the main logger, I get "When creating VisaTCPIP connection had to remove unknown arguments set([u'port'])".
The communication still works ok, and the system uses the correct port number when communicating with the instrument. But the instrument browser does not display the correct one.

**Comment by MatthieuDartiailh** [comment]
Closing as this is indeed an issue within ecpy itself. I will open a new ticket there.
