### ISSUE TITLE
LegacyVisaStarter: fix formatting of resource_name for VisaRaw connection

### ISSUE THREAD

**Issue by MatthieuDartiailh** [Ecpy/ecpy_hqc_legacy#32]
When using a VisaRaw connection the connection already provides a resource_name so there is no point in trying to format one.

As you were the ones to encounter this error would mend doing a PR @Qcircuits.

**Comment by Qcircuits** [comment]
Done!

**Comment by MatthieuDartiailh** [comment]
Fixed by #34
