### ISSUE TITLE
Measure can be overwritten by another in the queue

### ISSUE THREAD

**Issue by lcontami** [Ecpy/ecpy_hqc_legacy#38]
One way to partially protect against that is to check that no 2 measures with the same name and id are enqueued (if the save file name is defined using {meas_name}_{meas_id} then this will work).

This will have to be added to the InternalChecksHook.

Todo also: add in the documentation that one should use {meas_date}_{meas_name}_{meas_id} for the file name definition.

**Comment by MatthieuDartiailh** [comment]
This belongs in ecpy repo.

**Comment by lcontami** [comment]
Pffffffff that's true, sorry I'll move it
